name: openvla-oft
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - icu=75.1=he02047a_0
  - ld_impl_linux-64=2.44=h1aa0949_4
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.0=hee844dc_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.4=h26f9b46_0
  - pip=25.2=pyh8b19718_0
  - python=3.10.19=h3c07f61_2_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_hd72426e_102
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.1
      - accelerate==1.11.0
      - annotated-doc==0.0.3
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - array-record==0.8.1
      - astunparse==1.6.3
      - bddl==1.0.1
      - cachetools==6.2.1
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cloudpickle==2.1.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - diffusers==0.30.3
      - dlimp==0.0.1
      - docker-pycreds==0.4.0
      - draccus==0.8.0
      - easydict==1.9
      - egl-probe==1.0.2
      - einops==0.4.1
      - etils==1.13.0
      - evdev==1.9.2
      - exceptiongroup==1.3.0
      - fastapi==0.121.0
      - fastjsonschema==2.21.2
      - filelock==3.20.0
      - flash-attn==2.5.5
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - future==0.18.2
      - gast==0.6.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - glfw==2.10.0
      - google-auth==2.41.1
      - google-auth-oauthlib==1.2.3
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - gym==0.25.2
      - gym-notices==0.1.0
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - hydra-core==1.2.0
      - idna==3.11
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - iniconfig==2.3.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - json-numpy==2.1.1
      - jsonlines==4.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-core==5.9.1
      - jupytext==1.18.1
      - keras==2.15.0
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - libero==0.1.0
      - llvmlite==0.45.1
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.5.3
      - mdit-py-plugins==0.5.0
      - mdurl==0.1.2
      - mergedeep==1.3.4
      - ml-dtypes==0.2.0
      - mpmath==1.3.0
      - mujoco==3.3.7
      - mypy-extensions==1.1.0
      - nbformat==5.10.4
      - networkx==3.4.2
      - ninja==1.13.0
      - nltk==3.9.2
      - numba==0.62.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.3.1
      - omegaconf==2.3.0
      - opencv-python==4.6.0.66
      - openexr==3.4.3
      - openvla-oft==0.0.1
      - opt-einsum==3.4.0
      - packaging==25.0
      - pathtools==0.1.2
      - peft==0.11.1
      - pillow==12.0.0
      - platformdirs==4.5.0
      - pluggy==1.6.0
      - promise==2.3
      - protobuf==4.21.12
      - psutil==7.1.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pynput==1.8.1
      - pyopengl==3.1.10
      - pyparsing==3.2.5
      - pytest==8.4.2
      - python-dateutil==2.9.0.post0
      - python-xlib==0.33
      - pyyaml==6.0.3
      - pyyaml-include==1.4.1
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rich==14.2.0
      - robomimic==0.2.0
      - robosuite==1.4.1
      - rpds-py==0.28.0
      - rsa==4.9.1
      - safetensors==0.6.2
      - scipy==1.13.1
      - sentencepiece==0.1.99
      - sentry-sdk==2.43.0
      - setproctitle==1.3.7
      - shortuuid==1.0.13
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - starlette==0.49.3
      - sympy==1.14.0
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - tensorflow==2.15.0
      - tensorflow-addons==0.23.0
      - tensorflow-datasets==4.9.3
      - tensorflow-estimator==2.15.0
      - tensorflow-graphics==2021.12.3
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-metadata==1.17.2
      - termcolor==3.2.0
      - thop==0.1.1-2209072238
      - timm==0.9.10
      - tokenizers==0.19.1
      - toml==0.10.2
      - tomli==2.3.0
      - torch==2.2.0
      - torchaudio==2.2.0
      - torchvision==0.17.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.40.1
      - trimesh==4.9.0
      - triton==2.2.0
      - typeguard==2.13.3
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - wandb==0.22.3
      - werkzeug==3.1.3
      - wrapt==1.14.2
      - zipp==3.23.0
prefix: /home/server/miniconda3/envs/openvla-oft
